### ISSUE TITLE
Additional fields

### ISSUE THREAD

**Issue by rivella50** [fernan542/fl_country_code_picker#1]
Hi there,
thanks for offering the package.

What i'm missing are the following fields:
- favorite: list of country codes which will be shown on the very top of the list
- countryFilter: only show the countries in this list (when a user may only select from e.g. 5 countries in total)

I used the same names as your role model (package [country_code_picker](https://pub.dev/packages/country_code_picker)).
Would be great if you could add these fields, and hopefully you're gonna maintain this package - lots of other similar packages seem to be abandoned.

**Comment by fernan542** [comment]
Hello @rivella50, thanks for your interest. 
Sure I'll implement those updates this week. :)

**Comment by fernan542** [comment]
https://pub.dev/packages/fl_country_code_picker

Update: v0.0.2 🙂
- refactor: make class constable
- refactor: enable access to CountryCodes list without using a BuildContext
- feat: add option for hiding the search bar
- feat: add support for favorite countries
- feat: add support for countries filtering

**Comment by rivella50** [comment]
Thanks a lot!
