### ISSUE TITLE
Search not working when app localized

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [fernan542/fl_country_code_picker#10]
Hi, again @fernan542 ! Searching with localized app not working. I've checked your code and there was 
` availableCountryCodes
                ..clear()
                ..addAll(
                  List<CountryCode>.from(
                    baseList.where(
                      (c) =>
                          c.code.toLowerCase().contains(query.toLowerCase()) ||
                          c.dialCode
                              .toLowerCase()
                              .contains(query.toLowerCase()) ||
                          c.name.toLowerCase().contains(query.toLowerCase()),
                    ),
                  ),
                );
             ,` which is not getting localized name of  country code. I've tried to search Singapoore(in English). It's working fine. But when I switched to other languages, it's not giving results

**Comment by fernan542** [comment]
Hello, thanks for pointing out! I'll push a fix today.

**Comment by fernan542** [comment]
Fixed in new release! 🔥
https://pub.dev/packages/fl_country_code_picker/versions/0.1.2

Thanks!
