### ISSUE TITLE
update to intl intl: ^0.18.0

### ISSUE THREAD

**Issue by menezes85** [fernan542/fl_country_code_picker#11]
Thanks for this package, i would request update intl, 0.18.0 is out, and  force me to use 0.0.4, due incompability.

**Comment by fernan542** [comment]
Hello 👋. 
I'm using the version 0.18.0 of `intl` package. Try to use the version:
```yaml
fl_country_code_picker: ^0.1.2
```
If this doesn't work for you, can you show the error log when updating your pub?
Thanks!

**Comment by menezes85** [comment]
![image](https://user-images.githubusercontent.com/43157391/218203909-a69a5bae-bbdf-4bd4-bd3e-cc375a3a5bf5.png)

**Comment by menezes85** [comment]
package explicity requires intl 0.17, i cant upgrade , only way to solve that is override fl_country_code_picker to v 0.0.4.

**Comment by fernan542** [comment]
Do you upgraded your Flutter version lately? If so, try to;
1. Delete `pubspec.lock`.
2. Run `flutter update-packages --force-upgrade`

**Comment by menezes85** [comment]
Solved, after running command, thanks a lot!

**Comment by fernan542** [comment]
Thank you for using my package! 🤗
