### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FarukAyd** [fernan542/fl_country_code_picker#12]
Hi, when i upgrade the version ^0.1.2 an error occured: 

```
Exception has occurred.
_CastError (Null check operator used on a null value)

```
I startted new project and write code as like your example but after i tap on button just raised above error message...

The place error on **country_localization.dart** is:
```

  /// Reference for lookup objects that contain collections of localized values.
  static CountryLocalizations of(BuildContext context) {
    return Localizations.of<CountryLocalizations>(
      context,
      CountryLocalizations,
    )!; //_error line showing here_
 
```

**Comment by fernan542** [comment]
Hello! 👋 Thanks for using my package.
Starting from version `0.1.0`, the package supports localization.
Have you tried adding the required data for localization?

1. First, import the package and add an alias to prevent other import errors inside your file where it contains the `MaterialApp` widget.
```dart
import  'package:fl_country_code_picker/fl_country_code_picker.dart' as flc;
```
2. Add the following values at your app's `MaterialApp`.
```dart
MaterialApp(
	title: 'Your App',
	// Supported locales at the moment.
	// Cannot find your locale? Please make a request.
	supportedLocales: flc.supportedLocales.map((e) => Locale(e)),
	localizationsDelegates: const [
		// Package's localization delegate.
		flc.CountryLocalizations.delegate,
		GlobalWidgetsLocalizations.delegate, // optional
		GlobalMaterialLocalizations.delegate, // optional
		GlobalCupertinoLocalizations.delegate, // optional
	],
	// ... some omitted values
);
```

**Comment by FarukAyd** [comment]
Thanks for fast reply, as you said i didn't add localizationDelegates to my code. Now no problem, thanks again.

**Comment by fernan542** [comment]
Thank you! 
I'll be closing this for now. Feel free to re-open or create another issue.
