### ISSUE TITLE
Unable to customize country picker dialog

### ISSUE THREAD

**Issue by sharath-b-naik** [fernan542/fl_country_code_picker#13]
Hello, 
There is no option to custimise picker as mentioned in readme file.

Thank you.

**Comment by fernan542** [comment]
Hello!👋
You can only customize the Search bar's decoration, modal's Title, and some visibility  behavior for icons at the moment.
Check out some of them here:
https://github.com/fernan542/fl_country_code_picker#flcountrycodepicker

Are you expecting something? Can you elaborate it so we can discuss it here. 
Thanks!

I'm closing this issue for now, feel free to reopen.

**Comment by ghost** [comment]
@fernan542 a/t my requirement the country code should be displayed after the country text with one character space between them. Currently, it is displayed at the end of the **Row** and there is no option to customize the picker as mentioned in the readme file.


Need customization of the **list item row**!!!

Thank you.
