### ISSUE TITLE
The getter 'flagUri' isn't defined for the type 'CountryCode'.

### ISSUE THREAD

**Issue by sinhpn92** [fernan542/fl_country_code_picker#14]
Hi,

I have got error `The getter 'flagUri' isn't defined for the type 'CountryCode'.` when try to use custom flag image. Have any missing here?

Thank you.

**Comment by fernan542** [comment]
Hello 👋🏻
You can access the `flagUri` as a property of a `CountryCode` object.
Example:
```dart
    GestureDetector(
    onTap: () async {
        // Show the country code picker when tapped.
        final code = await countryPicker.showPicker(context: context);
        // Null check
        if (code != null)  { 
          print(code);
          // Access flagUri property.
          print(code.flagUri);
        }
    },
  /// Some omitted values.
```

**Comment by sinhpn92** [comment]
> Hello 👋🏻 You can access the `flagUri` as a property of a `CountryCode` object. Example:
> 
> ```dart
>     GestureDetector(
>     onTap: () async {
>         // Show the country code picker when tapped.
>         final code = await countryPicker.showPicker(context: context);
>         // Null check
>         if (code != null) print(code);
>        // Access flagUri property.
>       print(code.flagUri);
>     },
>   /// Some omitted values.
> ```

Thank you so much. I got it. I have installed wrong version :d

**Comment by sinhpn92** [comment]
Now I got error `Null check operator used on a null value`. Can you please help? @fernan542 Thank you

**Comment by fernan542** [comment]
That error means that the `code` is `null` or the user didn't select from the picker. 
In order to solve that, you need to check if the `code` is not null before you use it or any of the property.

```dart
        // Check if not null first.
        if (code != null) {
          // Here you're confident that code is not null, 
          // you can access its properties.
          print(code.flagUri);
        } 
```
 Another thing, in order to help you more, I suggest you paste your code and I'll check it. ☺️
 I edited my answer above because I forgot to add curly braces.
 Thanks!

**Comment by sinhpn92** [comment]
Thank you @fernan542 

This is my code to call the picker:
```
Future<void> _onFlagPressed() async {
    const countryPicker = FlCountryCodePicker();
    final code = await countryPicker.showPicker(context: context);
    if (code == null) return;
    setState(() {
      _countryCode = code;
    });
  }
```

And the picker dialog showing up, then I get the error:

<img width="394" alt="Screenshot 2023-05-31 at 10 02 46" src="https://github.com/fernan542/fl_country_code_picker/assets/9253441/8447233c-6a90-4354-b768-7d2188b38d39">

**Comment by fernan542** [comment]
What version are you using? Can you show the full error log at your console?

**Comment by sinhpn92** [comment]
@fernan542 This my version: `phone_number: ^2.0.0`

Error log here: 

<img width="1144" alt="Screenshot 2023-05-31 at 20 15 30" src="https://github.com/fernan542/fl_country_code_picker/assets/9253441/5568f904-9a59-4d73-b572-4709603fe619">

**Comment by fernan542** [comment]
Have you tried adding the localizations in your `MaterialApp`?

First, import the package and add an alias to prevent other import errors.
```dart
import  'package:fl_country_code_picker/fl_country_code_picker.dart' as flc;
```

Then add the following values at your app's MaterialApp:
```dart
MaterialApp(
	title: 'Your App',
	// Supported locales at the moment.
	// Cannot find your locale? Please make a request.
	supportedLocales: flc.supportedLocales.map((e) => Locale(e)),
	localizationsDelegates: const [
		// Package's localization delegate.
		CountryLocalizations.delegate,
		GlobalWidgetsLocalizations.delegate,
		GlobalMaterialLocalizations.delegate,
		GlobalCupertinoLocalizations.delegate,
	],
	// ... some omitted values
);
```

**Comment by sinhpn92** [comment]
ok got it. It's working now. Thank you so much @fernan542

**Comment by fernan542** [comment]
You're always welcome.
Thank you for using my package!
