### ISSUE TITLE
Select Multiple Countries

### ISSUE THREAD

**Issue by evanholt1** [fernan542/fl_country_code_picker#15]
Is there a way using this package to select multiple countries from the list at the same time?

I have the requirement that multiple countries may be selected from the dropdown at the same time. can this be achieved ?

**Comment by fernan542** [comment]
Yes it can be achieved but not at the current version.
I'll try to work on it if I'll have some free time this week, for the mean time, you can fork this repository and add those functionalities.

**Comment by evanholt1** [comment]
Ok. Thanks for your reply & continued work.
