### ISSUE TITLE
Late initialization error

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [fernan542/fl_country_code_picker#16]
While using package in crashlytics I'm getting "LateInitializationError: Field 'baseList' has already been initialized" error. And another question is why you've added "_initCountries" to "didChangeDependencies", not to "initState"?

**Comment by fernan542** [comment]
Hello, thanks for pointing out. I'll update the code.

**Comment by fernan542** [comment]
Should be fixed in [v0.1.3](https://pub.dev/packages/fl_country_code_picker/versions/0.1.3).
Please open this again if bug still occurs.
Thank you! 🎉
