### ISSUE TITLE
Modal with favorites error

### ISSUE THREAD

**Issue by fruts** [fernan542/fl_country_code_picker#21]
if i want to add 3 favorites country code i have this error 
`Trailing widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
'package:flutter/src/material/list_tile.dart':
Failed assertion: line 1323 pos 7: 'tileWidth != trailingSize.width || tileWidth == 0.0'`

Here is my code: 
<img width="493" alt="image" src="https://github.com/fernan542/fl_country_code_picker/assets/40259977/05f75017-1a35-46a2-9d96-e4d97ef9addd">

<img width="416" alt="image" src="https://github.com/fernan542/fl_country_code_picker/assets/40259977/0f50115c-e916-4119-9833-db0bfaf2ff82">

**Comment by fernan542** [comment]
Hello @fruts 👋
Thank you for pointing out. It is because of my PR <https://github.com/fernan542/fl_country_code_picker/commit/34d1bd24334008492402a5feca4f2a90fb9b8070>.

I'll revert the PR now and push the update.

**Comment by fernan542** [comment]
I've fix the issue at version [0.1.5](<https://pub.dev/packages/fl_country_code_picker/versions/0.1.5>).

Closing this for now, feel free to reopen.
Thank you for using my package! 🎉
