### ISSUE TITLE
Is Dark mode supported in library?

### ISSUE THREAD

**Issue by PrabhjotAndroid** [fernan542/fl_country_code_picker#22]
My App works in both light mode and dark mode. When i use dark mode, the dialogue is shown in white background and text not visible. can you please suggest?

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-10-03 at 07 06 59](https://github.com/fernan542/fl_country_code_picker/assets/15625027/7e28e0b2-610e-4bc0-9c8c-b5927e49bb17)

**Comment by fernan542** [comment]
Hello! 👋
Internally, the package uses a pre-defined `TextStyle` for the text widgets.
 
You can override this by passing your current theme context's TextStyle OR manually defined TextStyle.
The properties are:
`dialCodeTextStyle` and `countryTextStyle` of the `FlCountryCodePicker` class.

**Comment by PrabhjotAndroid** [comment]
yeah that is fine. I just want to set the background of bottom sheet to black in dark mode.

**Comment by fernan542** [comment]
Try setting the property of `backgroundColor` when calling the `showPicker` method.

```dart
// Show the country code picker when tapped.
        final code = await countryPicker.showPicker(context: context, backgroundColor: yourColor);
```

I'll update the Readme file to show the updated parameters.
