### ISSUE TITLE
A way for search and get Country Code without any manual action.  

### ISSUE THREAD

**Issue by MojtabaMohammadzadeh** [fernan542/fl_country_code_picker#28]
I needed that find a CountryCode befor user select anythings by a default number.
then I add this function in fl_country_code_picker.dart 

Future<CountryCode?> getByCode(String CodeNumber) async{
   final allCountryCodes = codes.map(CountryCode.fromMap).toList();
   for (var element in allCountryCodes) {

     if (element.dialCode == CodeNumber) {
       return element;
     }
   }
   return null; // Return null if the code is not found/ Return null if the code is not found
  }
  
  it works well for me . 
  I used it in my code like this 
  CountryCode? code =await countryPicker.getByCode(firstDigit);

**Comment by fernan542** [comment]
Hello @MojtabaMohammadzadeh 👋
The `CountryCode` model already have that functionality, added at [v1.0.7](https://github.com/fernan542/fl_country_code_picker/blob/master/CHANGELOG.md#017).

Example:
```dart
final phCountryCode = CountryCode.fromCode('PH');
if (phCountryCode == null) print("Ph country code not found!");
```
You also have the other [convenient methods](https://github.com/fernan542/fl_country_code_picker/blob/abe20ce961809db5bcc39327475b9e19cc629bd7/lib/src/models/country_code.dart#L38) such as;
`fromName`, `fromDialCode`

**Comment by MojtabaMohammadzadeh** [comment]
Thank you very much. It realy helped me . 
You are fantastic.

**Comment by fernan542** [comment]
Cool, I'm glad to hear that! :)
