### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by thEpisode** [fernan542/fl_country_code_picker#6]
Hi!, I want to change the title ("Select your contry") and hint search bar ("Country, Code or Dial Code") with my locale language, it is possible?

**Comment by fernan542** [comment]
Hello! 👋
I'll try to implement this alongside with this request:
https://github.com/fernan542/fl_country_code_picker/issues/5

Thank you!

**Comment by fernan542** [comment]
This issues are now addressed at commit [9f255cc](https://github.com/fernan542/fl_country_code_picker/commit/9f255cc49a56c01b0d67d74ca530c7e6d41183ab).

Last thing, I'll just update the CHANGELOG and Readme files.
Thank you!

**Comment by fernan542** [comment]
https://pub.dev/packages/fl_country_code_picker
Update v0.1.0 🥳

* feat: add support for localization
* feat: exposed the flagUri for flag image customization
* feat: add visibility flag for favorite icon
* refactor: enable customization for modal's title
* refactor: add Kosovo country

Thank you for using my package! 😊

**Comment by thEpisode** [comment]
Awesome! Thank you so much!
