### ISSUE TITLE
Localizations no arabic language supported

### ISSUE THREAD

**Issue by a7mdhanini** [fernan542/fl_country_code_picker#8]
Null check operator used on a null value when i use English.
also could you please add the Arabic language.

**Comment by fernan542** [comment]
Hello! 👋
> Null check operator used on a null value when i use English.

Can you add more information about the bug you encountered? What specific `English` language do you used?

> also could you please add the Arabic language.

Sure. I already found the files that I need to replicate to add the most of common languages used by different devices.

**Comment by fernan542** [comment]
I published a [new version](https://pub.dev/packages/fl_country_code_picker/versions/0.1.1), please check it out.

I'll be closing this for now.
Thank you for using my package! 🥳

**Comment by a7mdhanini** [comment]
￼

This is my code
    onTapPickCountry: () async {
                            final code = await const FlCountryCodePicker()
                                .showPicker(context: context);
                            if (code != null) {
                              provider.setCountryCode(code.dialCode.toString());
                            }
                          },

**Comment by fernan542** [comment]
Have you tried the new version?

If that doesn't helped you, does the error happen before or after you open the picker? If it's before, it is now fixed in the new version because I added a validator if the current selected device's country/region is not supported. Else, I guess it's in your business logic.

**Comment by a7mdhanini** [comment]
It happened after I used fl_country_code_picker: ^0.1.1
In the old version it was work just fine
Also I live in Jordan and my device language is English us
