### ISSUE TITLE
Flag and localization mismatch

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [fernan542/fl_country_code_picker#9]
Hi! I've noticed that in json files there is "ky.json"(which stands for Kyrgyzstan) file, but in assets flag "ky.png" represents England. Image "ky.png" should be deleted and "kg.png" file should be renamed to "ky.png". That would be correct

**Comment by fernan542** [comment]
Hello 👋
`ky` is for **[CAYMAN ISLANDS](https://www.iso.org/obp/ui/#iso:code:3166:KY)**. 
And the correct iso code for [KYRGYZSTAN](https://www.iso.org/obp/ui/#iso:code:3166:KG) is `kg`.
